import "~/styles/globals.css";
import { type Metadata } from "next";
import { TRPCReactProvider } from "~/trpc/react";
import { Poppins } from 'next/font/google';

const poppins = Poppins({
  weight: ['400', '700'],    
  style: ['normal', 'italic'], 
  subsets: ['latin'],         
  display: 'swap',            
});


export const metadata: Metadata = {
  title: "6O-Website",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={poppins.className}>
      <body>
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}


